### ISSUE TITLE
Dynamic permissions

### ISSUE THREAD

**Issue by ivan-kleshnin** [Avaq/permissionary#7]
Is it possible to setup permissions like **Can edit my own article** or **Can share an article to my friends** with Permissionary?

I guess not, because it's not compatible with reverse role lookup... Those are pretty standard-looking permissions, so when I wrote similar library some time ago I used filter functions with signatures like `(user, modelOfInterest) => Promise <canDoThisActionWithThisModel>` together with similar string constants like you did.

I'm interested in your opinion about it. Another option is to pre-generate permissions based on the database but it's probably a very bad idea (as most code-generation).

**Comment by Avaq** [comment]
There is an example of dynamic permissions in the `examples/express.js`:

https://github.com/Avaq/permissionary/blob/7c59564c88ca2fe1482cbd2ba95889a9f8c7e18e/examples/express.js#L102-L120

It's very common for me to have dynamic permissions distinguishing "owned" resources from other users' resources, eg:

```js
req.auth.has(`articles/edit/${req.session.id === req.params.userId ? 'self' : 'other'}`)
```

Now you can assign `articles/edit/self` to regular users, and `articles/edit/*` to, say, content moderators.

**Comment by ivan-kleshnin** [comment]
Thank you!

How do you avoid code duplication for `articles/edit/self` and `articles/edit/*` route handlers? I can imagine a few approaches but maybe you can share a time-tested one (I don't have big experience with Express).

**Comment by Avaq** [comment]
I'm not sure what code duplication you are referring to. Could you provide an example of the duplicated code?

**Comment by ivan-kleshnin** [comment]
```
app.post("/articles/self, (req, res) => {
  // Code A
})

app.post("/articles/, (req, res) => {
  // Code B
})
```

Code A will be almost the same as Code B.

**Comment by Avaq** [comment]
Ah. I see the misconception here. `articles/edit/self` is **not a route**. It's a single permission. Your code would not have duplication:

```js
app.put("/articles/:articleId", (req, res, next) => {
  res.locals.database.get('articles', {id: req.params.articleId}).then(article => {
    const author = res.locals.session.userId === article.authorId ? 'self' : 'other';
    //Dynamically checked permission below!
    //Author can be "self" or "other", so this single endpoint checks two permissions
    if(res.locals.auth.has(`articles/edit/${author}`)) {
      res.locals.database.update('articles', {id: req.params.articleId}, req.body);
    } else {
      next(new Error('Insufficient permissions'))
    }
  }, next)
})
```

A similar approach is shown in the express example I mentioned earlier. You can clone this repo and run the express example, and poke around in it a bit.

Notice how I haven't abstracted anything in my example. It's quite possible to implement this `(user, modelOfInterest) => Promise <canDoThisActionWithThisModel>` function on top of Permissionary.

**Comment by ivan-kleshnin** [comment]
Got it, thanks for your time!
